"""add_order_and_balance_tables

Revision ID: addda63b6974
Revises: 873f1bd632e2
Create Date: 2025-12-28 08:16:57.343036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addda63b6974'
down_revision: Union[str, Sequence[str], None] = '873f1bd632e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('free', sa.Float(), nullable=True),
    sa.Column('locked', sa.Float(), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'asset', 'is_paper', name='uix_balance_account')
    )
    op.create_index(op.f('ix_balances_asset'), 'balances', ['asset'], unique=False)
    op.create_index(op.f('ix_balances_exchange'), 'balances', ['exchange'], unique=False)
    op.create_index(op.f('ix_balances_id'), 'balances', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_amount', sa.Float(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_exchange'), 'orders', ['exchange'], unique=False)
    op.create_index(op.f('ix_orders_is_paper'), 'orders', ['is_paper'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_paper'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_balances_id'), table_name='balances')
    op.drop_index(op.f('ix_balances_exchange'), table_name='balances')
    op.drop_index(op.f('ix_balances_asset'), table_name='balances')
    op.drop_table('balances')
    # ### end Alembic commands ###
